services:
  ss-parser:
    build:
      context: .
    container_name: ss-parser
    env_file:
      - .env
    volumes:
      - ./data:/data
    command: python main.py
    healthcheck:
      test: ["CMD", "python", "healthcheck.py"]
      interval: 600s
      timeout: 5s
      retries: 3
      start_period: 15s
    restart: unless-stopped